### PR TITLE
search -> binary and linear

### PR DESCRIPTION
**Pull request by Paras-Mayur8055**
i hope you will accept my request 
thank you

### CODE REVIEW

**Review by Lancelot03 — CHANGES_REQUESTED** [review]
I think the binary search code is not correct please can you fix it 😊.

**Comment by Paras-Mayur8055** [comment]
> I think the binary search code is not correct please can you fix it 😊.

ohh sorry let me check

**Comment by Paras-Mayur8055** [comment]
> I think the binary search code is not correct please can you fix it 😊.

thx for pointing out

**Comment by Paras-Mayur8055** [comment]
> I think the binary search code is not correct please can you fix it 😊.

done  you can check it out

**Review by Paras-Mayur8055 — COMMENTED** [review]
changes done :)

**Comment by Paras-Mayur8055** [comment]
@Lancelot03 are you on linkedin lets connect 

my id is paras mayur you can search i will be on top results (2.4k) followers

**Review by Lancelot03 — APPROVED** [review]

**Comment by Lancelot03** [comment]
@Paras-Mayur8055 Thanks for contributing 😊. And here is my LinkedIn https://www.linkedin.com/in/harsh-singh-943ba01a3/

**Pull request merged**
