### PR TITLE
added more comptetitve code

### PR DESCRIPTION
**Pull request by warriorwizard**
@Lancelot03 added more competitive codes to the repository

### CODE REVIEW

**Comment by warriorwizard** [comment]
could u please let me know of similar repos i can contribute to

**Comment by Lancelot03** [comment]
You can contribute to [vivian-dai](https://github.com/vivian-dai/Hacktoberfest-2022-Repos) and [inspirezonetech](https://github.com/inspirezonetech/TeachMePythonLikeIm5) 😊😊.

**Comment by warriorwizard** [comment]
u haven't merged it yet

**Comment by Lancelot03** [comment]
And your commits were blocked because your account has not had its SHH key or it was expired, so to tackle this problem you have to assign a new SHH key. https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification will help you.

**Comment by Lancelot03** [comment]
> u haven't merged it yet

Because the merging of this PR is blocked.

**Comment by Lancelot03** [comment]
Screenshot 2022-10-16 220059

**Comment by DevilANANDGupta** [comment]
class Solution(object):
    def nextPermutation(self, nums):
        """
        :type nums: List[int]
        :rtype: void Do not return anything, modify nums in-place instead.
        """

        i = j = len(nums)-1
        while i > 0 and nums[i]<=nums[i-1]:
            i-=1
        i-=1
        if i<0:
            nums.reverse()
            return
        
        while j>i and nums[j]<=nums[i]:
            j-=1
        
        nums[i],nums[j] = nums[j], nums[i]
        
        k,l = i+1, len(nums)-1
        
        while k<l:
            nums[k],nums[l] = nums[l], nums[k]
            k+=1
            l-=1

**Pull request closed without merging**
