### PR TITLE
Update 4Sum.py

### PR DESCRIPTION
**Pull request by DevilANANDGupta**
to be simple and less complexity

### CODE REVIEW

**Review by Lancelot03 — APPROVED** [review]

**Comment by Lancelot03** [comment]
I'm not labeling this PR as hacktoberfest because this kind of commit was not approved and is not in Hacktoberfest rules.

**Comment by DevilANANDGupta** [comment]
then could you tell me what type of commit is valid

**Comment by DevilANANDGupta** [comment]
to be simple and less complexity
import collections
class Solution:
    def fourSum(self, nums: List[int], target: int) -> List[List[int]]:
        nums.sort()
        result = []
        for i in range(len(nums) - 3):
            if i and nums[i] == nums[i - 1]:
                continue
            for j in range(i + 1, len(nums) - 2):
                if j != i + 1 and nums[j] == nums[j - 1]:
                    continue
                total = target - nums[i] - nums[j]
                left, right = j + 1, len(nums) - 1
                while left < right:
                    if nums[left] + nums[right] == total:
                        result.append([nums[i], nums[j], nums[left], nums[right]])
                        right -= 1
                        left += 1
                        while left < right and nums[left] == nums[left - 1]:
                            left += 1
                        while left < right and nums[right] == nums[right + 1]:
                            right -= 1
                    elif nums[left] + nums[right] > total:
                        right -= 1
                    else:
                        left += 1
        return result

**Comment by DevilANANDGupta** [comment]
Sorry but now I updated Please Label my PR

**Pull request merged**
