### PR TITLE
Create binary.py

### PR DESCRIPTION
**Pull request by DevilANANDGupta**
Compared to binary search for sorted list, the key is to check twice when before recursions:

Compare mid-point with left end
Compare target with the interval[left end, mid point].

now this is the right code

### CODE REVIEW

**Comment by DevilANANDGupta** [comment]
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        l,r = 0, len(nums)-1
        def bs(l,r,target):
            if l==r:
                if nums[l]==target:
                    return l
                else:
                    return -1
            m = (l+r)//2
            if nums[m]==target:
                return m
            if nums[m]<nums[l]:
                if nums[m]<target<=nums[r]:
                    return bs(m+1, r, target)
                else:
                    return bs(l,m-1,target)
            else:
                if nums[l]<=target<nums[m]:
                    return bs(l,m-1,target)
                else:
                    return bs(m+1,r,target)
            
            return -1
        return bs(l,r,target)

**Comment by Lancelot03** [comment]
Yeah, that code was also correct but there were indentation mistakes.

**Review by DevilANANDGupta — COMMENTED** [review]
checked

**Review by Lancelot03 — APPROVED** [review]

**Comment by DevilANANDGupta** [comment]
what can I do for hacktoberfest badges and swags ?

**Pull request merged**
